apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: richard-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /app1
            backend:
              service:
                name: hello-minikube
                port:
                  number: 8010

